Main svc
AGolykh/java-explore-with-me pull request #2
Opened 2023-07-05 11:08 UTC by AGolykh

2023-07-06 08:24 UTC, TomattmanYandex requested changes
Комменты в коде
дополнительно повторюсь
 есть большое различие между методами приватными, админскими и просто методами , нге стоит решать их перегрузкой, ибо читается очень тяжело, и шанс ошибки очень большой, я как программист исправляющий код, могу в будущем увидеть разные варианты перегруженного метода, и решить что можно использовать любой
а так вроде как все отлично

2023-07-06 08:24 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/event/EventService.java
> +        Event updatedEvent = makeUpdatedEvent(null, eventId, eventAdminUpdateRequestDto);
в спецификации есть требование 

дата начала изменяемого события должна быть не ранее чем за час от даты публикации. (Ожидается код ошибки 409)\n- событие можно публиковать, только если оно в состоянии ожидания публикации (Ожидается код ошибки 409)\n- событие можно отклонить, только если оно еще не опубликовано (Ожидается код ошибки 409)",

2023-07-06 08:24 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/event/EventService.java
> +    public List<EventFullDto> getAll(EventSearchPublicParams eventSearchPublicParams,
так как тут есть большая разница между публичными и админскими методами, лучше не просто перегрузить методы, а так же отобразить это в имени метода, чтобы путаницы не было

2023-07-06 08:24 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/event/EventService.java
> +                .map(eventMapper::toEventFullDto)
ты же используешь бибилиотечку для маппинга, у них обычно можно определить метод мапинга, который мапит сразу лист, и тогда не придётся вот так вот мапить каждый элемент списка

2023-07-06 08:24 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/event/EventRepository.java
> +    List<Event> findEventsByParams(@Param("text") String text,
вот снова два метода, с одинаковым именем, но внутри несущих довольно таки значительную логику, лучше отобразить эту разницу в названии чтобы не возникло путаницы

2023-07-06 08:24 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
не очень хорошо, что null pointer обрабатывается как не найдено, он может возникнуть по множеству причин, не только если обьект не будет найден

2023-07-06 08:24 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/event/model/EventSearchPublicParams.java
> +public class EventSearchPublicParams {
это скорее дто чем модель

2023-07-06 08:24 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/event/EventService.java
> +    public EventFullDto getEventByUserEventId(Long userId, Long eventId, HttpServletRequest httpServletRequest) {
тут же ищестся по двум параметрам, следовательно в имени стоит добавить And  а то очень непонятно

2023-07-06 08:24 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/event/EventRepository.java
> +    List<Event> findAllByInitiator_Id(Long userId, Pageable pageable);
давай уберем из имени метода нижние подчеркивания, работать будет и без них но уж очень выделяется

2023-07-06 08:25 UTC, TomattmanYandex requested changes
Комменты в коде
дополнительно повторюсь
есть большое различие между методами приватными, админскими и просто методами , нге стоит решать их перегрузкой, ибо читается очень тяжело, и шанс ошибки очень большой, я как программист исправляющий код, могу в будущем увидеть разные варианты перегруженного метода, и решить что можно использовать любой

2023-07-06 08:38 UTC, AGolykh commented on main-service/src/main/java/ru/practicum/event/EventRepository.java
> +    List<Event> findAllByInitiator_Id(Long userId, Pageable pageable);
Убрал во всех репах

2023-07-06 08:44 UTC, AGolykh commented on main-service/src/main/java/ru/practicum/event/EventService.java
> +    public EventFullDto getEventByUserEventId(Long userId, Long eventId, HttpServletRequest httpServletRequest) {
переименовал

2023-07-06 08:44 UTC, AGolykh commented on main-service/src/main/java/ru/practicum/event/model/EventSearchParams.java
> +public class EventSearchParams {
Переименовал

2023-07-06 09:56 UTC, AGolykh commented on main-service/src/main/java/ru/practicum/event/EventService.java
> +        Event updatedEvent = makeUpdatedEvent(null, eventId, eventAdminUpdateRequestDto);
разделил методы для привата и админа

2023-07-06 10:05 UTC, AGolykh commented on main-service/src/main/java/ru/practicum/event/EventService.java
> +    public List<EventFullDto> getAll(EventSearchPublicParams eventSearchPublicParams,
Переименовал сервисные методы

2023-07-06 10:44 UTC, AGolykh commented on main-service/src/main/java/ru/practicum/event/EventService.java
> +                .map(eventMapper::toEventFullDto)
Добавил метод для конвертации в лист дто

2023-07-06 10:46 UTC, AGolykh commented on main-service/src/main/java/ru/practicum/event/EventRepository.java
> +    List<Event> findEventsByParams(@Param("text") String text,
переименовал все

2023-07-06 11:19 UTC, AGolykh commented on main-service/src/main/java/ru/practicum/category/Category.java
> +    private String name;
Указал уникальные поля во всех классах, в базе все ограничения прописаны

2023-07-07 05:29 UTC, AGolykh commented on main-service/src/main/java/ru/practicum/exception/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.NOT_FOUND)
Создал новое исключение

2023-07-07 15:35 UTC, TomattmanYandex approved these changes
Принято

2023-07-09 07:57 UTC, merged